/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEncodingLangScopeProvider extends DelegatingScopeProvider {
}
