/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalEncodingLangParser;
import org.xtext.example.services.EncodingLangGrammarAccess;

public class EncodingLangParser extends AbstractAntlrParser {

	@Inject
	private EncodingLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEncodingLangParser createParser(XtextTokenStream stream) {
		return new InternalEncodingLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EncodingLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EncodingLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
