/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.encodingLang.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.encodingLang.EncodingLangPackage;
import org.xtext.example.encodingLang.ExactMapping;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exact Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExactMappingImpl extends MappingImpl implements ExactMapping
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExactMappingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EncodingLangPackage.Literals.EXACT_MAPPING;
  }

} //ExactMappingImpl
