/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.encodingLang.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.encodingLang.Alias;
import org.xtext.example.encodingLang.EncodingLangPackage;
import org.xtext.example.encodingLang.Mapping;
import org.xtext.example.encodingLang.SourceMapping;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Source Mapping</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.encodingLang.impl.SourceMappingImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.encodingLang.impl.SourceMappingImpl#getAliases <em>Aliases</em>}</li>
 *   <li>{@link org.xtext.example.encodingLang.impl.SourceMappingImpl#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SourceMappingImpl extends MinimalEObjectImpl.Container implements SourceMapping
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAliases() <em>Aliases</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAliases()
   * @generated
   * @ordered
   */
  protected EList<Alias> aliases;

  /**
   * The cached value of the '{@link #getMappings() <em>Mappings</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMappings()
   * @generated
   * @ordered
   */
  protected EList<Mapping> mappings;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SourceMappingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EncodingLangPackage.Literals.SOURCE_MAPPING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EncodingLangPackage.SOURCE_MAPPING__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Alias> getAliases()
  {
    if (aliases == null)
    {
      aliases = new EObjectContainmentEList<Alias>(Alias.class, this, EncodingLangPackage.SOURCE_MAPPING__ALIASES);
    }
    return aliases;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Mapping> getMappings()
  {
    if (mappings == null)
    {
      mappings = new EObjectContainmentEList<Mapping>(Mapping.class, this, EncodingLangPackage.SOURCE_MAPPING__MAPPINGS);
    }
    return mappings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EncodingLangPackage.SOURCE_MAPPING__ALIASES:
        return ((InternalEList<?>)getAliases()).basicRemove(otherEnd, msgs);
      case EncodingLangPackage.SOURCE_MAPPING__MAPPINGS:
        return ((InternalEList<?>)getMappings()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EncodingLangPackage.SOURCE_MAPPING__NAME:
        return getName();
      case EncodingLangPackage.SOURCE_MAPPING__ALIASES:
        return getAliases();
      case EncodingLangPackage.SOURCE_MAPPING__MAPPINGS:
        return getMappings();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EncodingLangPackage.SOURCE_MAPPING__NAME:
        setName((String)newValue);
        return;
      case EncodingLangPackage.SOURCE_MAPPING__ALIASES:
        getAliases().clear();
        getAliases().addAll((Collection<? extends Alias>)newValue);
        return;
      case EncodingLangPackage.SOURCE_MAPPING__MAPPINGS:
        getMappings().clear();
        getMappings().addAll((Collection<? extends Mapping>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EncodingLangPackage.SOURCE_MAPPING__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EncodingLangPackage.SOURCE_MAPPING__ALIASES:
        getAliases().clear();
        return;
      case EncodingLangPackage.SOURCE_MAPPING__MAPPINGS:
        getMappings().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EncodingLangPackage.SOURCE_MAPPING__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EncodingLangPackage.SOURCE_MAPPING__ALIASES:
        return aliases != null && !aliases.isEmpty();
      case EncodingLangPackage.SOURCE_MAPPING__MAPPINGS:
        return mappings != null && !mappings.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SourceMappingImpl
