/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ide;

import org.xtext.example.ide.AbstractEncodingLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EncodingLangIdeModule extends AbstractEncodingLangIdeModule {
}
