/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import encoding_rules_base.ui.internal.Encoding_rules_baseActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EncodingLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Encoding_rules_baseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Encoding_rules_baseActivator.getInstance().getInjector(Encoding_rules_baseActivator.ORG_XTEXT_EXAMPLE_ENCODINGLANG);
	}
	
}
