/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.encodingLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conversion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.encodingLang.Conversion#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.encodingLang.Conversion#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.encodingLang.EncodingLangPackage#getConversion()
 * @model
 * @generated
 */
public interface Conversion extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.encodingLang.EncodingLangPackage#getConversion_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.encodingLang.Conversion#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.encodingLang.Mapping}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mappings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see org.xtext.example.encodingLang.EncodingLangPackage#getConversion_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<Mapping> getMappings();

} // Conversion
