/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.encodingLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transliteration Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.encodingLang.EncodingLangPackage#getTransliterationMapping()
 * @model
 * @generated
 */
public interface TransliterationMapping extends Mapping
{
} // TransliterationMapping
