/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example;

import org.xtext.example.AbstractEncodingLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EncodingLangRuntimeModule extends AbstractEncodingLangRuntimeModule {
}
