/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example;

import org.xtext.example.EncodingLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EncodingLangStandaloneSetup extends EncodingLangStandaloneSetupGenerated {
  public static void doSetup() {
    new EncodingLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
