/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.validation;

import org.xtext.example.validation.AbstractEncodingLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EncodingLangValidator extends AbstractEncodingLangValidator {
}
