/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.xtext.example.encodingLang.Alias;
import org.xtext.example.encodingLang.Mapping;
import org.xtext.example.encodingLang.Model;
import org.xtext.example.encodingLang.SourceMapping;
import org.xtext.example.services.EncodingLangGrammarAccess;

@SuppressWarnings("all")
public class EncodingLangFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private EncodingLangGrammarAccess _encodingLangGrammarAccess;
  
  protected void _format(final Model model, @Extension final IFormattableDocument document) {
    EList<SourceMapping> _elements = model.getElements();
    for (final SourceMapping sourceMapping : _elements) {
      document.<SourceMapping>format(sourceMapping);
    }
  }
  
  protected void _format(final SourceMapping s, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(document.prepend(this.textRegionExtensions.regionFor(s).keyword("source"), _function), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(document.prepend(this.textRegionExtensions.regionFor(s).keyword("{"), _function_2), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(s).keyword("}"), _function_4);
    EList<Alias> _aliases = s.getAliases();
    for (final Alias alias : _aliases) {
      final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
        it.indent();
      };
      final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
      };
      document.append(document.prepend(this.textRegionExtensions.regionFor(alias).keyword("alias"), _function_5), _function_6);
    }
    EList<Mapping> _mappings = s.getMappings();
    for (final Mapping mapping : _mappings) {
      final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
        it.setSpace("\t");
      };
      document.<Mapping>prepend(document.<Mapping>append(mapping, _function_7), _function_8);
    }
  }
  
  protected void _format(final Alias a, @Extension final IFormattableDocument document) {
  }
  
  public void format(final Object a, final IFormattableDocument document) {
    if (a instanceof XtextResource) {
      _format((XtextResource)a, document);
      return;
    } else if (a instanceof Alias) {
      _format((Alias)a, document);
      return;
    } else if (a instanceof Model) {
      _format((Model)a, document);
      return;
    } else if (a instanceof SourceMapping) {
      _format((SourceMapping)a, document);
      return;
    } else if (a instanceof EObject) {
      _format((EObject)a, document);
      return;
    } else if (a == null) {
      _format((Void)null, document);
      return;
    } else if (a != null) {
      _format(a, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(a, document).toString());
    }
  }
}
