/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.generator;

import org.eclipse.xtend.lib.annotations.Accessors;
import org.eclipse.xtext.xbase.lib.Pure;

@SuppressWarnings("all")
public class State {
  @Accessors
  private int counter;
  
  public State(final int counter) {
    this.counter = counter;
  }
  
  @Pure
  public int getCounter() {
    return this.counter;
  }
  
  public void setCounter(final int counter) {
    this.counter = counter;
  }
}
